### ISSUE TITLE
Being told items Aren't in the AUR when they are

### ISSUE THREAD

**Issue by xXWhackerXx-GitHub** [HanabishiRecca/aur-check-updates#1]
I'm running Garuda and just did updates and had to temporarily remove Aur-Check-Updates so one dependency could update and allow the rest of the updates to do so. Reinstalled and running 1.1.0-1. I'm curious as to why it would tell me the below aren't in the AUR when I checked some of them individually they are in the AUR. Thanks

```
~  aur-check-updates                                           ✔  49s  06:44:17
:: Checking AUR updates...
no updates
electron22-bin-debug                 22.3.27-4           => [not found in AUR]
emby-server-beta-debug               4.9.0.30-1          => [not found in AUR]
faudio-debug                         24.09-1             => [not found in AUR]
kde-service-menu-reimage             2.5-1.4             => [not found in AUR]
kde-servicemenus-komparemenu         0.1-3.4             => [not found in AUR]
kde-servicemenus-officeconverter     1-1.4               => [not found in AUR]
kde-servicemenus-pdf-encrypt-decrypt 1-1                 => [not found in AUR]
kde-servicemenus-sendtodesktop       1-1.4               => [not found in AUR]
kdelibs4support-debug                5.116.0-2           => [not found in AUR]
kdesignerplugin-debug                5.116.0-2           => [not found in AUR]
kf5-servicemenus-rootactions-git     r16.cdfe53f-3       => [not found in AUR]
khotkeys                             5.27.10-1           => [not found in AUR]
kpeoplevcard                         0.1-2               => [not found in AUR]
kquickcharts5                        5.115.0-1           => [not found in AUR]
krunner5-debug                       5.115.0-4           => [not found in AUR]
lib32-faudio-debug                   24.06-1             => [not found in AUR]
libretro-duckstation                 2105-2              => [not found in AUR]
localsend-debug                      1.14.0-3            => [not found in AUR]
opera-developer-debug                114.0.5272.0-1      => [not found in AUR]
pacseek-debug                        1.8.2-3             => [not found in AUR]
pyside2-debug                        5.15.13-2           => [not found in AUR]
qgpgme-qt5-debug                     1.23.2-5            => [not found in AUR]
rest-debug                           0.8.1+r4+ge5ee6ef-2 => [not found in AUR]
sonarr-develop-debug                 4.0.9.2342-1        => [not found in AUR]
```

**Comment by HanabishiRecca** [comment]
> I'm running Garuda and just did updates and had to temporarily remove Aur-Check-Updates so one dependency could update and allow the rest of the updates to do so.

That's intended. `alpm` crate uses a fixed version of `libalpm.so` and would fail to run or build with a wrong version.
So when pacman gets a major update (from `libalpm.so=14` to `libalpm.so=15` in this case), you will need to uninstall the app, update pacman, and then install the app again. There is no way around it unfortunately.



> I'm curious as to why it would tell me the below aren't in the AUR when I checked some of them individually they are in the AUR.

They are not in AUR. `-debug` packages are never in AUR or official repos, as they are essentially a byproduct of `debug` makepkg flag. In fact you are probably want to remove them and [disable `debug` in you `makepkg.conf`](https://wiki.archlinux.org/title/Makepkg#Disable_debug_packages_and_LTO).

Other packages are also is not in AUR. So I don't know how you checked it.

**Comment by HanabishiRecca** [comment]
> `-debug` packages are never in AUR

Although, a new option to ignore packages with specified suffix could be useful. Say `--ignoresuffix '-debug'`.

**Comment by HanabishiRecca** [comment]
Made the app to filter `-debug` packages by default.
